[images]
  remote_images = [
    "https://ext.same-assets.com/*",
    "https://static.tildacdn.com/*",
    "https://thb.tildacdn.com/*"
  ]

[build]
  command = "bun run build"
  publish = "dist"

[dev]
  command = "bun run dev"
  port = 5173
  targetPort = 5173
  publish = "dist"
  autoLaunch = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
